package dev.itseternity.chatfilter.chat;

import dev.itseternity.chatfilter.ChatFilterPlugin;
import dev.itseternity.chatfilter.filter.AdvertisingFilter;
import dev.itseternity.chatfilter.filter.AutoMuteFilter;
import dev.itseternity.chatfilter.filter.CaptchaFilter;
import dev.itseternity.chatfilter.filter.Filter;
import dev.itseternity.chatfilter.filter.MoveFilter;
import dev.itseternity.chatfilter.filter.ParrotFilter;
import dev.itseternity.chatfilter.filter.SwearFilter;
import com.google.common.cache.Cache;
import com.google.common.cache.CacheBuilder;
import lombok.Getter;
import lombok.Setter;
import org.bukkit.entity.Player;

import java.util.*;
import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;

@Getter
@Setter
public class ChatManager {

    private static final int FIVE_MINUTES_TICKS = 300 * 20; // 300s = 5 minutes

    private final Cache<UUID, UUID> autoMutes = CacheBuilder.newBuilder()
            .expireAfterAccess(10, TimeUnit.MINUTES)
            .build();
    private final Map<UUID, ChatMessage> lastMessage = new HashMap<>();
    private final Set<Filter> filters = new HashSet<>();
    private final Set<String> curses = new HashSet<>();
    private final Set<String> autoMuteWords = new HashSet<>();
    private final Set<String> blacklistedWords = new HashSet<>();
    private final Set<String> whitelistedWords = new HashSet<>();

    private boolean globalMute = false;
    private boolean autoMute = false;
    private int chatDelay = 0;

    public ChatManager(ChatFilterPlugin plugin) {
        populate();

        Stream.of(
                new SwearFilter(plugin),
                new AdvertisingFilter(plugin),
                new AutoMuteFilter(plugin),
                new MoveFilter(plugin),
                new ParrotFilter(plugin),
                new CaptchaFilter(plugin)
        ).forEach(filters::add);

        new FilterUpdateTask(plugin).runTaskTimerAsynchronously(plugin, FIVE_MINUTES_TICKS, FIVE_MINUTES_TICKS);
    }

    public void autoMute(Player player) {
        autoMutes.put(player.getUniqueId(), player.getUniqueId());
    }

    public boolean isAutoMuted(Player player) {
        return autoMutes.getIfPresent(player.getUniqueId()) != null;
    }

    public void removeAutoMute(Player player) {
        autoMutes.invalidate(player.getUniqueId());
    }

    public boolean addAutoMuteWord(String name) {
        return autoMuteWords.add(name);
    }

    public boolean removeAutoMuteWord(String name) {
        return autoMuteWords.remove(name);
    }

    public void setLastMessage(Player player, ChatMessage message) {
        lastMessage.put(player.getUniqueId(), message);
    }

    public Optional<ChatMessage> getLastMessage(Player player) {
        return Optional.ofNullable(lastMessage.get(player.getUniqueId()));
    }

    @Deprecated
    private void populate() {
        if (!curses.isEmpty()) {
            return;
        }
        curses.add("2 girls 1 cup");
        curses.add("2g1c");
        curses.add("5h1t");
        curses.add("5hit");
        curses.add("a55");
        curses.add("anal");
        curses.add("anus");
        curses.add("ar5e");
        curses.add("arse");
        curses.add("ass");
        curses.add("b!tch");
        curses.add("b00bs");
        curses.add("b17ch");
        curses.add("b1tch");
        curses.add("ballsack");
        curses.add("bangbros");
        curses.add("barenaked");
        curses.add("bastard");
        curses.add("bbw");
        curses.add("bdsm");
        curses.add("beaner");
        curses.add("beastial");
        curses.add("bellend");
        curses.add("bestial");
        curses.add("biatch");
        curses.add("bimbos");
        curses.add("bitch");
        curses.add("blow job");
        curses.add("blowjob");
        curses.add("bollocks");
        curses.add("bondage");
        curses.add("boner");
        curses.add("boob");
        curses.add("booobs");
        curses.add("boooobs");
        curses.add("booooobs");
        curses.add("booty");
        curses.add("bosta");
        curses.add("breast");
        curses.add("bronha");
        curses.add("bs");
        curses.add("bugger");
        curses.add("busty");
        curses.add("butt");
        curses.add("c0ck");
        curses.add("cabaa");
        curses.add("cagar");
        curses.add("camel toe");
        curses.add("camgirl");
        curses.add("chink");
        curses.add("cl1t");
        curses.add("clit");
        curses.add("clitoris");
        curses.add("cnut");
        curses.add("cock");
        curses.add("cok");
        curses.add("coon");
        curses.add("coprolagnia");
        curses.add("coprophilia");
        curses.add("cornhole");
        curses.add("creampie");
        curses.add("cum");
        curses.add("cunt");
        curses.add("cuzo");
        curses.add("cyalis");
        curses.add("cyberfuc");
        curses.add("d1ck");
        curses.add("darkie");
        curses.add("date rape");
        curses.add("daterape");
        curses.add("deep throat");
        curses.add("deepthroat");
        curses.add("dendrophilia");
        curses.add("dick");
        curses.add("dildo");
        curses.add("dingleberries");
        curses.add("dingleberry");
        curses.add("dink");
        curses.add("dlck");
        curses.add("hump");
        curses.add("duche");
        curses.add("ejaculate");
        curses.add("ejaculating");
        curses.add("ejaculation");
        curses.add("ejakulate");
        curses.add("erotic");
        curses.add("f u c k");
        curses.add("f u c k e r");
        curses.add("f4g");
        curses.add("f4nny");
        curses.add("f_u_c_k");
        curses.add("fag");
        curses.add("fanny");
        curses.add("fcuk");
        curses.add("fecal");
        curses.add("feck");
        curses.add("feg");
        curses.add("fegget");
        curses.add("felch");
        curses.add("feltch");
        curses.add("female squirting");
        curses.add("femdom");
        curses.add("fetiche");
        curses.add("ffs");
        curses.add("fgt");
        curses.add("figging");
        curses.add("fingerbang");
        curses.add("fingering");
        curses.add("fisting");
        curses.add("fking");
        curses.add("foder");
        curses.add("fook");
        curses.add("foot fetish");
        curses.add("footjob");
        curses.add("frotting");
        curses.add("fuck");
        curses.add("fuder");
        curses.add("fuk");
        curses.add("futanari");
        curses.add("fux");
        curses.add("g-spot");
        curses.add("gang bang");
        curses.add("gangbang");
        curses.add("gay");
        curses.add("genitals");
        curses.add("girl on");
        curses.add("girl on top");
        curses.add("girls gone wild");
        curses.add("giromba");
        curses.add("goatcx");
        curses.add("god damn");
        curses.add("goddamn");
        curses.add("gokkun");
        curses.add("golden shower");
        curses.add("goo girl");
        curses.add("goodpoop");
        curses.add("goregasm");
        curses.add("gozar");
        curses.add("gozo");
        curses.add("grelho");
        curses.add("grope");
        curses.add("guro");
        curses.add("h1tl3r");
        curses.add("h1tler");
        curses.add("hand job");
        curses.add("handjob");
        curses.add("hentai");
        curses.add("heshe");
        curses.add("hitl3r");
        curses.add("hitler");
        curses.add("hoar");
        curses.add("hoare");
        curses.add("hoer");
        curses.add("homo");
        curses.add("homoerotic");
        curses.add("honkey");
        curses.add("hooker");
        curses.add("hore");
        curses.add("horniest");
        curses.add("horny");
        curses.add("hot carl");
        curses.add("hot chick");
        curses.add("how to kill");
        curses.add("how to murder");
        curses.add("huge fat");
        curses.add("humping");
        curses.add("incest");
        curses.add("intercourse");
        curses.add("jack off");
        curses.add("jack-off");
        curses.add("jackoff");
        curses.add("jail bait");
        curses.add("jailbait");
        curses.add("jap");
        curses.add("jelly donut");
        curses.add("jerk off");
        curses.add("jerk-off");
        curses.add("jigaboo");
        curses.add("jiggaboo");
        curses.add("jiggerboo");
        curses.add("jiromba");
        curses.add("jism");
        curses.add("jiz");
        curses.add("jizm");
        curses.add("jizz");
        curses.add("juggs");
        curses.add("k y s");
        curses.add("kanker");
        curses.add("kawk");
        curses.add("kct");
        curses.add("kike");
        curses.add("kill urself");
        curses.add("kill your self");
        curses.add("kill yourself");
        curses.add("killyour self");
        curses.add("killyourself");
        curses.add("kinbaku");
        curses.add("kinkster");
        curses.add("kinky");
        curses.add("knob");
        curses.add("knobbing");
        curses.add("knobead");
        curses.add("knobed");
        curses.add("knobend");
        curses.add("knobhead");
        curses.add("knobjocky");
        curses.add("knobjokey");
        curses.add("kock");
        curses.add("kondum");
        curses.add("kondums");
        curses.add("krl");
        curses.add("kum");
        curses.add("kummer");
        curses.add("kumming");
        curses.add("kums");
        curses.add("kunilingus");
        curses.add("kut");
        curses.add("kys");
        curses.add("l3i+ch");
        curses.add("l3itch");
        curses.add("labia");
        curses.add("leather restraint");
        curses.add("leather straight jacket");
        curses.add("lemon party");
        curses.add("lolita");
        curses.add("lovemaking");
        curses.add("lusting");
        curses.add("m0f0");
        curses.add("m0fo");
        curses.add("m45terbate");
        curses.add("ma5terb8");
        curses.add("ma5terbate");
        curses.add("make me come");
        curses.add("male squirting");
        curses.add("masochist");
        curses.add("master-bate");
        curses.add("masterb8");
        curses.add("masterbat*");
        curses.add("masterbat3");
        curses.add("masterbate");
        curses.add("masterbation");
        curses.add("masterbations");
        curses.add("masturbate");
        curses.add("menage a trois");
        curses.add("merda");
        curses.add("mija");
        curses.add("mijo");
        curses.add("milf");
        curses.add("missionary position");
        curses.add("mo-fo");
        curses.add("mof0");
        curses.add("mofo");
        curses.add("mound of venus");
        curses.add("mr hands");
        curses.add("muff");
        curses.add("muff diver");
        curses.add("muffdiving");
        curses.add("mutha");
        curses.add("muthafecker");
        curses.add("muther");
        curses.add("n1gga");
        curses.add("n1gger");
        curses.add("naba");
        curses.add("nambla");
        curses.add("nawashi");
        curses.add("nazi");
        curses.add("negro");
        curses.add("neonazi");
        curses.add("ni gg er");
        curses.add("nig");
        curses.add("nig nog");
        curses.add("nimphomania");
        curses.add("ninfeta");
        curses.add("nipple");
        curses.add("nipples");
        curses.add("nobhead");
        curses.add("nsfw images");
        curses.add("nude");
        curses.add("nudity");
        curses.add("nutsack");
        curses.add("nympho");
        curses.add("nymphomania");
        curses.add("octopussy");
        curses.add("omorashi");
        curses.add("one cup two girls");
        curses.add("one guy one jar");
        curses.add("orgasim");
        curses.add("orgasm");
        curses.add("orgy");
        curses.add("p0rn");
        curses.add("paedophile");
        curses.add("paki");
        curses.add("panties");
        curses.add("panty");
        curses.add("pecker");
        curses.add("pedo");
        curses.add("pegging");
        curses.add("pen15");
        curses.add("penis");
        curses.add("pentelho");
        curses.add("pepeca");
        curses.add("phuck");
        curses.add("phuk");
        curses.add("phuq");
        curses.add("pimpis");
        curses.add("piroca");
        curses.add("piss");
        curses.add("piss pig");
        curses.add("pisspig");
        curses.add("playboy");
        curses.add("pleasure chest");
        curses.add("pole smoker");
        curses.add("ponyplay");
        curses.add("poon");
        curses.add("poontang");
        curses.add("poop chute");
        curses.add("poopchute");
        curses.add("porn");
        curses.add("porra");
        curses.add("prick");
        curses.add("prince albert piercing");
        curses.add("prostitute");
        curses.add("pthc");
        curses.add("pu$$y");
        curses.add("pube");
        curses.add("pubes");
        curses.add("punany");
        curses.add("punheta");
        curses.add("pusse");
        curses.add("pussi");
        curses.add("pussies");
        curses.add("pussy");
        curses.add("pusy");
        curses.add("puta");
        curses.add("puto");
        curses.add("queaf");
        curses.add("queef");
        curses.add("queer");
        curses.add("quim");
        curses.add("r4p3");
        curses.add("r4pe");
        curses.add("raghead");
        curses.add("raging boner");
        curses.add("rape");
        curses.add("raping");
        curses.add("rapist");
        curses.add("rectum");
        curses.add("retard");
        curses.add("reverse cowgirl");
        curses.add("rimjaw");
        curses.add("rimjob");
        curses.add("rimming");
        curses.add("roludo");
        curses.add("rosy palm");
        curses.add("rosy palm and her 5 sisters");
        curses.add("rusty trombone");
        curses.add("s hit");
        curses.add("s&m");
        curses.add("s.o.b.");
        curses.add("s_h_i_t");
        curses.add("sadism");
        curses.add("sadist");
        curses.add("santorum");
        curses.add("sapato");
        curses.add("scat");
        curses.add("schlong");
        curses.add("scissoring");
        curses.add("screwing");
        curses.add("scroat");
        curses.add("scrote");
        curses.add("scrotum");
        curses.add("semen");
        curses.add("sex");
        curses.add("sh!+");
        curses.add("sh!t");
        curses.add("sh*t");
        curses.add("sh1t");
        curses.add("shag");
        curses.add("shat");
        curses.add("shaved beaver");
        curses.add("shaved pussy");
        curses.add("shemale");
        curses.add("shi+");
        curses.add("shibari");
        curses.add("shit");
        curses.add("shota");
        curses.add("shrimping");
        curses.add("siht");
        curses.add("skank");
        curses.add("skeet");
        curses.add("slanteye");
        curses.add("slut");
        curses.add("sluts");
        curses.add("smegma");
        curses.add("smut");
        curses.add("snatch");
        curses.add("snowballing");
        curses.add("sodomize");
        curses.add("sodomy");
        curses.add("spic");
        curses.add("splooge");
        curses.add("splooge moose");
        curses.add("spooge");
        curses.add("spread legs");
        curses.add("spunk");
        curses.add("strap on");
        curses.add("strapon");
        curses.add("strappado");
        curses.add("strip club");
        curses.add("style doggy");
        curses.add("suicide girls");
        curses.add("sultry women");
        curses.add("suruba");
        curses.add("swastika");
        curses.add("swinger");
        curses.add("t1tt1e5");
        curses.add("t1tties");
        curses.add("tainted love");
        curses.add("taste my");
        curses.add("tea bagging");
        curses.add("teets");
        curses.add("teez");
        curses.add("tesao");
        curses.add("testical");
        curses.add("testicle");
        curses.add("teta");
        curses.add("tetas");
        curses.add("tezao");
        curses.add("threesome");
        curses.add("throating");
        curses.add("tied up");
        curses.add("tight white");
        curses.add("tit");
        curses.add("tongue in a");
        curses.add("topless");
        curses.add("tosser");
        curses.add("towelhead");
        curses.add("tranny");
        curses.add("tribadism");
        curses.add("tub girl");
        curses.add("tubgirl");
        curses.add("turd");
        curses.add("tushy");
        curses.add("tw4t");
        curses.add("twat");
        curses.add("twathead");
        curses.add("twatty");
        curses.add("twink");
        curses.add("twinkie");
        curses.add("two girls one cup");
        curses.add("twunt");
        curses.add("twunter");
        curses.add("upskirt");
        curses.add("v14gra");
        curses.add("v1gra");
        curses.add("vagin");
        curses.add("vagina");
        curses.add("viado");
        curses.add("viagra");
        curses.add("vibrador");
        curses.add("vulva");
        curses.add("w00se");
        curses.add("wang");
        curses.add("wank");
        curses.add("wanker");
        curses.add("wanky");
        curses.add("whoar");
        curses.add("whore");
        curses.add("xavaska");
        curses.add("xereca");
        curses.add("xota");
        curses.add("xoxota");
        curses.add("xxt");
    }
}

